# Generated by Django 5.2.4 on 2025-07-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hafıza Kartı',
                'verbose_name_plural': 'Hafıza Kartları',
                'db_table': 'flashcards',
            },
        ),
        migrations.CreateModel(
            name='FlashcardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hafıza Kartı Destesi',
                'verbose_name_plural': 'Hafıza Kartı Desteleri',
                'db_table': 'flashcard_decks',
            },
        ),
        migrations.CreateModel(
            name='FlashcardDeckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'flashcard_deck_items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FlashcardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField(choices=[(1, 'Çok Kolay'), (2, 'Kolay'), (3, 'Orta'), (4, 'Zor'), (5, 'Çok Zor')], default=3)),
                ('repetition_count', models.IntegerField(default=0)),
                ('interval_days', models.IntegerField(default=1)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('next_review_date', models.DateTimeField()),
                ('last_reviewed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hafıza Kartı İlerlemesi',
                'verbose_name_plural': 'Hafıza Kartı İlerlemeleri',
                'db_table': 'flashcard_progress',
            },
        ),
    ]
