# Generated by Django 5.2.4 on 2025-07-17 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0002_initial'),
        ('flashcards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='exams.topic'),
        ),
        migrations.AddField(
            model_name='flashcarddeck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_decks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flashcarddeckitem',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.flashcarddeck'),
        ),
        migrations.AddField(
            model_name='flashcarddeckitem',
            name='flashcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.flashcard'),
        ),
        migrations.AddField(
            model_name='flashcarddeck',
            name='flashcards',
            field=models.ManyToManyField(through='flashcards.FlashcardDeckItem', to='flashcards.flashcard'),
        ),
        migrations.AddField(
            model_name='flashcardprogress',
            name='flashcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.flashcard'),
        ),
        migrations.AddField(
            model_name='flashcardprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='flashcarddeckitem',
            unique_together={('deck', 'flashcard')},
        ),
        migrations.AlterUniqueTogether(
            name='flashcardprogress',
            unique_together={('user', 'flashcard')},
        ),
    ]
