# Generated by Django 5.2.4 on 2025-07-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('daily_question_enabled', models.BooleanField(default=True)),
                ('task_reminder_enabled', models.BooleanField(default=True)),
                ('goal_reminder_enabled', models.BooleanField(default=True)),
                ('achievement_enabled', models.BooleanField(default=True)),
                ('system_enabled', models.BooleanField(default=True)),
                ('study_reminder_enabled', models.BooleanField(default=True)),
                ('exam_reminder_enabled', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bildirim Ayarı',
                'verbose_name_plural': 'Bildirim Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(db_index=True, max_length=128)),
                ('notification_type', models.CharField(choices=[('daily_question', 'Günlük Soru'), ('task_reminder', 'Görev Hatırlatması'), ('goal_reminder', 'Hedef Hatırlatması'), ('achievement', 'Başarı'), ('system', 'Sistem'), ('study_reminder', 'Çalışma Hatırlatması'), ('exam_reminder', 'Sınav Hatırlatması')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['firebase_uid', 'is_read'], name='notificatio_firebas_f68510_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
