# Generated by Django 5.2.4 on 2025-07-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='extra_data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='notificationsettings',
            old_name='achievement_enabled',
            new_name='achievement_notifications',
        ),
        migrations.RenameField(
            model_name='notificationsettings',
            old_name='daily_question_enabled',
            new_name='daily_reminders',
        ),
        migrations.RenameField(
            model_name='notificationsettings',
            old_name='email_notifications',
            new_name='email_enabled',
        ),
        migrations.RenameField(
            model_name='notificationsettings',
            old_name='exam_reminder_enabled',
            new_name='exam_reminders',
        ),
        migrations.RenameField(
            model_name='notificationsettings',
            old_name='goal_reminder_enabled',
            new_name='push_enabled',
        ),
        migrations.RenameField(
            model_name='notificationsettings',
            old_name='push_notifications',
            new_name='study_reminders',
        ),
        migrations.RenameField(
            model_name='notificationsettings',
            old_name='study_reminder_enabled',
            new_name='weekly_reports',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='action_url',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='quiet_hours_end',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='quiet_hours_start',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='system_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='task_reminder_enabled',
        ),
        migrations.AlterField(
            model_name='notification',
            name='firebase_uid',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('daily_question', 'Günlük Soru'), ('task_reminder', 'Görev Hatırlatması'), ('goal_reminder', 'Hedef Hatırlatması'), ('achievement', 'Başarı'), ('system', 'Sistem'), ('study_reminder', 'Çalışma Hatırlatması'), ('exam_reminder', 'Sınav Hatırlatması'), ('quick_solution', 'Hızlı Çözüm')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
