# Generated by Django 5.2.4 on 2025-07-28 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=200, verbose_name='Görev Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('task_type', models.CharField(choices=[('study', 'Çalışma'), ('practice', 'Pratik'), ('review', 'Tekrar'), ('exam', 'Sınav'), ('flashcard', 'Flashcard'), ('custom', 'Özel')], default='study', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek')], default='medium', max_length=10)),
                ('estimated_duration', models.IntegerField(help_text='Dakika cinsinden', verbose_name='Tahmini Süre')),
                ('actual_duration', models.IntegerField(blank=True, help_text='Gerçekleşen süre (dakika)', null=True)),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(default=django.utils.timezone.now, verbose_name='Bitiş Tarihi')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='Ders')),
                ('topic', models.CharField(blank=True, max_length=100, verbose_name='Konu')),
            ],
            options={
                'verbose_name': 'Günlük Görev',
                'verbose_name_plural': 'Günlük Görevler',
                'ordering': ['-created_at'],
            },
        ),
    ]
