# Generated by Django 5.2.4 on 2025-07-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['subject', 'level', 'order', 'name'], 'verbose_name': 'Konu', 'verbose_name_plural': 'Konular'},
        ),
        migrations.AddField(
            model_name='topic',
            name='full_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='topic',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['subject', 'parent_topic'], name='topics_subject_9f8b00_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['level'], name='topics_level_031d19_idx'),
        ),
    ]
