# Generated by Django 5.2.4 on 2025-07-29 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_topic_options_topic_full_path_topic_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('exam_date', models.DateField()),
                ('exam_type', models.CharField(choices=[('tyt', 'TYT'), ('ayt', 'AYT'), ('dil', 'Dil'), ('msu', 'MSÜ'), ('alan', 'Alan Sınavı')], max_length=10)),
                ('normal_duration', models.IntegerField(help_text='Normal süre (dakika)')),
                ('actual_duration', models.IntegerField(help_text='Öğrencinin bitirdiği süre (dakika)')),
                ('difficulty', models.CharField(choices=[('easy', 'Kolay'), ('medium', 'Orta'), ('hard', 'Zor')], default='medium', max_length=10)),
                ('total_questions', models.IntegerField()),
                ('total_marked', models.IntegerField(help_text='Toplam işaretlenen soru sayısı')),
                ('total_correct', models.IntegerField()),
                ('total_wrong', models.IntegerField()),
                ('total_net', models.DecimalField(decimal_places=2, help_text='Net puan', max_digits=5)),
                ('notes', models.TextField(blank=True, help_text='Öğrenci notları')),
                ('is_completed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to='exams.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deneme Kaydı',
                'verbose_name_plural': 'Deneme Kayıtları',
                'db_table': 'exam_records',
                'ordering': ['-exam_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'exam_date'], name='exam_record_user_id_080cb8_idx'), models.Index(fields=['exam_type', 'subject'], name='exam_record_exam_ty_be7b7b_idx'), models.Index(fields=['created_at'], name='exam_record_created_46c80e_idx')],
            },
        ),
    ]
