# Generated by Django 5.2.4 on 2025-07-29 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='examrecord',
            name='exam_record_exam_ty_be7b7b_idx',
        ),
        migrations.RemoveIndex(
            model_name='examrecord',
            name='exam_record_created_46c80e_idx',
        ),
        migrations.RemoveField(
            model_name='examrecord',
            name='actual_duration',
        ),
        migrations.RemoveField(
            model_name='examrecord',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='examrecord',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='examrecord',
            name='subject',
        ),
        migrations.AddField(
            model_name='examrecord',
            name='exam_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.subject', verbose_name='Deneme Dersi'),
        ),
        migrations.AddField(
            model_name='examrecord',
            name='exam_topics',
            field=models.ManyToManyField(blank=True, to='exams.topic', verbose_name='Deneme Konuları'),
        ),
        migrations.AddField(
            model_name='examrecord',
            name='student_duration',
            field=models.IntegerField(blank=True, help_text='Öğrencinin bitirme süresi (dakika)', null=True, verbose_name='Öğrenci Süresi'),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Kolay'), ('medium', 'Orta'), ('hard', 'Zor')], max_length=10, null=True, verbose_name='Zorluk'),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='exam_date',
            field=models.DateField(verbose_name='Deneme Tarihi'),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='exam_name',
            field=models.CharField(max_length=200, verbose_name='Deneme Adı'),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='exam_type',
            field=models.CharField(choices=[('tyt', 'TYT'), ('ayt', 'AYT'), ('dil', 'Dil'), ('msu', 'MSÜ')], max_length=10, verbose_name='Deneme Türü'),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='normal_duration',
            field=models.IntegerField(blank=True, help_text='Normal süre (dakika)', null=True, verbose_name='Normal Süre'),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='total_correct',
            field=models.IntegerField(blank=True, null=True, verbose_name='Toplam Doğru'),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='total_marked',
            field=models.IntegerField(blank=True, null=True, verbose_name='Toplam İşaretleme'),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='total_net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Toplam Net'),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='total_questions',
            field=models.IntegerField(blank=True, null=True, verbose_name='Soru Sayısı'),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='total_wrong',
            field=models.IntegerField(blank=True, null=True, verbose_name='Toplam Yanlış'),
        ),
        migrations.AddIndex(
            model_name='examrecord',
            index=models.Index(fields=['exam_type', 'exam_subject'], name='exam_record_exam_ty_4f5270_idx'),
        ),
    ]
