# Generated by Django 5.2.4 on 2025-07-29 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konu', models.CharField(max_length=100, verbose_name='Konu')),
                ('ders', models.CharField(max_length=50, verbose_name='Ders')),
                ('mesaj', models.TextField(verbose_name='Kullanıcı Mesajı')),
                ('fotograf', models.ImageField(upload_to='quick_solutions/', verbose_name='Fotoğraf')),
                ('vision_text', models.TextField(blank=True, null=True, verbose_name='Vision AI Metni')),
                ('gemini_response', models.TextField(blank=True, null=True, verbose_name='Gemini Cevabı')),
                ('is_processed', models.BooleanField(default=False, verbose_name='İşlendi mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='İşlenme Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_solutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hızlı Çözüm',
                'verbose_name_plural': 'Hızlı Çözümler',
                'ordering': ['-created_at'],
            },
        ),
    ]
