# Generated by Django 5.2.4 on 2025-07-30 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0003_initial'),
        ('exams', '0005_remove_examrecord_exam_record_exam_ty_be7b7b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userquestionanswer',
            options={'verbose_name': 'Soru Cevabı', 'verbose_name_plural': 'Soru Cevapları'},
        ),
        migrations.RenameField(
            model_name='studyplan',
            old_name='completed_date',
            new_name='completed_at',
        ),
        migrations.RenameField(
            model_name='userprogress',
            old_name='total_questions_solved',
            new_name='total_exam_attempts',
        ),
        migrations.RenameField(
            model_name='userquestionanswer',
            old_name='answered_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='current_level',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='last_exam_score',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='target_score',
        ),
        migrations.AddField(
            model_name='studyplan',
            name='topics',
            field=models.ManyToManyField(blank=True, to='exams.topic'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='average_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='strong_subjects',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='weak_subjects',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='estimated_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='priority',
            field=models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.subject'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='last_study_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('study', 'Çalışma'), ('practice', 'Pratik'), ('review', 'Tekrar'), ('exam', 'Sınav')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('questions_answered', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('focus_score', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Çalışma Oturumu',
                'verbose_name_plural': 'Çalışma Oturumları',
                'db_table': 'study_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SpacedRepetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Kolay'), ('medium', 'Orta'), ('hard', 'Zor')], default='medium', max_length=10)),
                ('interval_days', models.IntegerField(default=1)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('repetition_count', models.IntegerField(default=0)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('next_review', models.DateTimeField(blank=True, null=True)),
                ('correct_count', models.IntegerField(default=0)),
                ('wrong_count', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaced_repetitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spaced Repetition',
                'verbose_name_plural': 'Spaced Repetitions',
                'db_table': 'spaced_repetitions',
                'ordering': ['next_review'],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
