# Generated by Django 5.2.4 on 2025-07-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cinsiyet',
            field=models.CharField(blank=True, choices=[('erkek', 'Erkek'), ('kadin', 'Kadın'), ('diger', 'Diğer')], max_length=10, null=True, verbose_name='Cinsiyet'),
        ),
        migrations.AddField(
            model_name='user',
            name='dogum_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AddField(
            model_name='user',
            name='yas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Yaş'),
        ),
    ]
